config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show]
  end

  resources :posts, only: %i[new create destroy] do
    resources :comments, only: %i[index new create destroy]
    resources :likes, only: %i[create destroy]
  end

  namespace :api do
    devise_for :users, as: 'api', controllers: { sessions: 'api/sessions', registrations: 'api/registrations' }

    resources :users, only: %i[] do
      resources :posts, only: %i[index]
    end
  
    resources :posts, only: %i[] do
      resources :comments, only: %i[index create]
    end
  end

  # Defines the root path route ("/")
  root "users#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id', inverse_of: :comments
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id', inverse_of: :comments

  validates :user, presence: true
  validates :post, presence: true
  validates :text, presence: true

  after_create :increment_comments_counter
  after_destroy :decrement_comments_counter

  private

  def increment_comments_counter
    post.increment!(:commentsCounter)
  end

  def decrement_comments_counter
    post.decrement!(:commentsCounter)
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  protect_from_forgery with: :null_session
  skip_before_action :verify_authenticity_token, only: :create
  before_action :authenticate_user

  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments
    render json: @comments, status: :ok
  end

  def create
    @current_user = User.find(@current_user_id)
    @comment = @current_user.comments.new(comment_params)
    @post = Post.find(params[:post_id])
    @comment.post = @post
    if @comment.save
      render json: @comment, status: :ok
    else
      render json: { error: 'Error creating the comment.' }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @current_user = current_user
    @post = Post.find(params[:post_id])
  end

  def create
    @current_user = current_user
    @comment = current_user.comments.new(comment_params)
    @post = Post.find(params[:post_id])
    @comment.post = @post
    if @comment.save
      flash[:success] = 'Comment saved successfully'
      redirect_to user_post_url(@post.user.id, @post.id)
    else
      flash.now[:error] = @comment.errors.full_messages.to_sentence
      render :new, locals: { user: @current_user, post: @post }, status: 422
    end
  end

  def destroy
    @comment = Comment.find(params[:post][:comment_id])
    comment_user_id = @comment.user.id
    @comment.destroy
    redirect_to user_url(comment_user_id)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/views/comments/_comment_card.html.erb
<div class="card__box-comment">
  <div class="comment__desc">
    <%= tag.h4("#{comment.user.name}:", class: 'card__title') %>
    <%= tag.p(comment.text, class: 'card__text') %>
  </div>
  <% if can? :destroy, comment %>
  <div class="owner__admin">
    <%= button_to 'Delete', post_comment_path(comment.post.id, comment.id), params: { post: { post_id: comment.post.id, comment_id: comment.id }}, method: :delete %>
  </div>
  <% end %>
</div>

app/views/comments/new.html.erb
<div class="form__container">
<%= tag.h1('New Comment', class: 'form__title') %>
<%= render 'layouts/alert', flash: flash %>
<%= form_with model: [@post, Comment.new] do |f| %>
  <%= f.text_area :text, rows: 10, placeholder: 'Enter your comment' %>
  <%= f.submit 'Save' %>
<% end %>
</div>