config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show]
  end

  resources :posts, only: %i[new create destroy] do
    resources :comments, only: %i[index new create destroy]
    resources :likes, only: %i[create destroy]
  end

  namespace :api do
    devise_for :users, as: 'api', controllers: { sessions: 'api/sessions', registrations: 'api/registrations' }

    resources :users, only: %i[] do
      resources :posts, only: %i[index]
    end
  
    resources :posts, only: %i[] do
      resources :comments, only: %i[index create]
    end
  end

  # Defines the root path route ("/")
  root "users#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :posts, class_name: 'Post', foreign_key: 'user_id', inverse_of: :user, dependent: :destroy
  has_many :comments, class_name: 'Comment', foreign_key: 'user_id', inverse_of: :user, dependent: :destroy
  has_many :likes, class_name: 'Like', foreign_key: 'user_id', inverse_of: :user, dependent: :destroy

  validates :name, presence: true
  validates :bio, presence: true
  validates :photo, presence: true
  validates :postsCounter, presence: true, numericality: { only_integer: true },
                           comparison: { greater_than_or_equal_to: 0 }

  after_initialize :default_values

  def most_recent_posts(items = 3)
    posts.order(created_at: :desc).take(items)
  end

  def posts_desc_order
    posts.order(created_at: :desc)
  end

  def generate_jwt
    JWT.encode({ id:,
                 exp: 60.days.from_now.to_i },
               Rails.application.secrets.secret_key_base)
  end

  private

  def default_values
    return unless new_record?

    self.bio ||= 'Enter your abstract bio here.'
    self.photo ||= 'user-profile.png'
    self.postsCounter ||= 0
    self.role ||= 'default'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(id: :asc)
    @current_user = current_user
  end

  def show
    @current_user = current_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_post.html.erb
<li class="list-group-item my-3 d-flex flex-column gap-2 border-top">

  <h4><%= post.title %></h4>

  <p><%= post.text %></p>

  <div class="align-self-end">
    <button type="button" class="btn btn-primary">
      Comments:
      <span class="badge bg-secondary">
        <%= post.commentsCounter  ? post.commentsCounter : 0 %>
      </span>
    </button>
    <button type="button" class="btn btn-primary">
      Likes:
      <span class="badge bg-secondary">
        <%= post.likesCounter ? post.likesCounter  : 0 %>
      </span>
    </button>
  </div>
</li>

app/views/users/_user.html.erb
<li class="list-group-item my-3 d-flex justify-content-around align-items-center flex-wrap gap-2 border-top">

  <a href="/users/<%= user.id %>">
    <%= content_tag(:div, tag.img(src: user.photo, alt: "#{user.name}'s photo", width: '150px'), class: 'card') %>
  </a>

  <h2><%= user.name %></h2>

  <button type="button" class="btn btn-primary align-self-end">
    Number of posts:
    <span class="badge bg-secondary">
      <%= user.post_counter ? user.post_counter : 0 %>
    </span>
  </button>

</li>

app/views/users/_user_card.html.erb
<div class="card__box card__box-user">
  <div class="card__image">
    <%= image_tag user.photo, alt: "#{user.name}'s photo" %>
  </div>
  <div class="card__info">
    <%= tag.h1(user.name, class: 'card__title') %>
    <p class="card__counters">Number of posts: <%= tag.span(user.postsCounter) %></p>
  </div>
  <%= link_to '', user_path(user.id), id: "link_user-#{user.id}", class: 'card__hidden-link' %>
</div>

app/views/users/index.html.erb
<%= render partial: 'user_card', collection: @users, as: :user %>

app/views/users/show.html.erb
<%= content_tag(:div, content_tag(:a, 'Edit Profile', href: edit_user_registration_path), class: 'card__box-subnav') %>
<%= render 'user_card', user: @user %>
<%= content_tag(:div, tag.p(@user.bio), class: 'card__box') %>
<%= render partial: 'posts/post_card', collection: @user.most_recent_posts, as: :post, locals: { detailed: false } %>
<%= link_to 'See all posts', user_posts_path(@user.id), class: 'btn btn-center' %>