config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show]
  end

  resources :posts, only: %i[new create destroy] do
    resources :comments, only: %i[index new create destroy]
    resources :likes, only: %i[create destroy]
  end

  namespace :api do
    devise_for :users, as: 'api', controllers: { sessions: 'api/sessions', registrations: 'api/registrations' }

    resources :users, only: %i[] do
      resources :posts, only: %i[index]
    end
  
    resources :posts, only: %i[] do
      resources :comments, only: %i[index create]
    end
  end

  # Defines the root path route ("/")
  root "users#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id', inverse_of: :posts
  has_many :comments, class_name: 'Comment', foreign_key: 'post_id', inverse_of: :post, dependent: :destroy
  has_many :likes, class_name: 'Like', foreign_key: 'post_id', inverse_of: :post, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :text, presence: true
  validates :commentsCounter, presence: true, numericality: { only_integer: true },
                              comparison: { greater_than_or_equal_to: 0 }
  validates :likesCounter, presence: true, numericality: { only_integer: true },
                           comparison: { greater_than_or_equal_to: 0 }

  after_create :increment_posts_counter
  after_destroy :decrement_posts_counter

  def most_recent_comments(items = 5)
    comments.order(created_at: :desc).take(items)
  end

  private

  def increment_posts_counter
    user.increment!(:postsCounter)
  end

  def decrement_posts_counter
    user.decrement!(:postsCounter)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts_desc_order
    render json: @posts, status: :ok
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @current_user = current_user
    @user = User.find(params[:user_id])
    @posts_and_comments = @user.posts_desc_order.includes(:comments)
  end

  def show
    @current_user = current_user
    @post = Post.find(params[:id])
  end

  def new
    @current_user = current_user
  end

  def create
    @current_user = current_user
    @post = @current_user.posts.new(post_params)
    @post.commentsCounter = 0
    @post.likesCounter = 0
    if @post.save
      flash[:success] = 'Post saved successfully'
      redirect_to user_posts_url(@current_user.id)
    else
      flash.now[:error] = @post.errors.full_messages.to_sentence
      render :new, locals: { user: @current_user }, status: 422
    end
  end

  def destroy
    @post = Post.find(params[:post][:post_id])
    post_user_id = @post.user.id
    @post.destroy
    redirect_to user_url(post_user_id)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_add_comment.html.erb
<%= form_with(model: [ post.author, post.author.comments.build ], url: "/users/#{post.author.id}/posts/#{post.id}/comments") do |form| %>

  <div class="mb-3">
    <%= form.text_field :text, class:"form-control", placeholder:"Add a comment" %>
  </div>

  <div>
    <%= form.submit class:'btn btn-primary' %>
  </div>

<% end %>

app/views/posts/_add_like.html.erb
<%= form_with url: "/users/#{post.author.id}/posts/#{post.id}/likes" do |form| %>
  <%= form.submit "Like", class: "btn btn-primary mt-2" %>
    <span class="badge bg-secondary p-2">
      <%= post.likesCounter? post.likesCounter  : 0 %>
    </span>
<% end %>

app/views/posts/_form.html.erb
<%= form_with model: Post.new do |form| %>

  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |message| %>
      <div class="alert alert-danger" role="alert">
        <%= message %> S
      </div>
    <% end %>       
  <% end %>

 <div class="mb-3">
    <% form.label :title %>
    <%= form.text_field :title, class:"form-control", placeholder:" Title of the post" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :text, class:"form-control", placeholder:"Content of the post" %>
  </div>

  <div>
    <%= form.submit class:'btn btn-primary' %>
  </div>

<% end %>

app/views/posts/_post.html.erb
<li class="list-group-item my-3 border-top">

  <a href="/users/<%= @user.id %>/posts/<%= post.id %>" class="text-reset text-decoration-none">
    <div class="d-flex flex-column gap-2">
      <h4><%= post.title %></h4>

      <p><%= post.text %></p>

      <div class="align-self-end">
        <button type="button" class="btn btn-primary">
          Comments:
          <span class="badge bg-secondary">
            <%= post.commentsCounter  ? post.commentsCounter : 0 %>
          </span>
        </button>
        <button type="button" class="btn btn-primary" disable>
          Likes:
          <span class="badge bg-secondary">
            <%= post.likesCounter ? post.likesCounter  : 0 %>
          </span>
        </button>
      </div>

      <h4> Comments </h4>
  
      <ul class="list-group">
        <% if post.comments.length > 0 %>
          <% post.comments.each do |comment| %>
          <li class="list-group-item"><%= comment.author.name %> : <%= comment.text %></li>
          <% end %>
        <% else %>
          <li class="list-group-item">No comments</li>
        <% end %>
      </ul>
      
    </div>
  </a>
</li>

app/views/posts/_post_card.html.erb
<div class="card__box card__box-post">
  <%= link_to tag.h2(post.title + (detailed ? " by #{post.user.name}" : ''), class: 'card__title'), user_post_path(post.user.id, post.id), class: 'link', id: "link_post-#{post.id}" %>
  <%= content_tag(:div, post.text, class: ['card__text', ('truncated-text' unless detailed)]) %>
  <div class="card__counters <%= 'card__counters-detailed' if detailed %>">
    <div class="counter__comments">
      <%= button_to "Comments: #{post.commentsCounter}", new_post_comment_path(post.id), method: :get, id: "comments_post-#{post.id}" %>
    </div>
    <div class="counter__likes">
      <% like = @current_user.likes.find_by(post: post) %>
      <% if like.nil? %>
        <%= button_to "Likes: #{post.likesCounter}", post_likes_path(post.id), params: { like: { post_id: post.id }}, method: :post, id: "likes_post-#{post.id}" %>
      <% else %>
        <%= button_to "Unlike: #{post.likesCounter}", post_like_path(post.id, like.id), params: { like: { post_id: post.id, like_id: like.id }} , method: :delete, id: "likes_post-#{post.id}" %>
      <% end %>
    </div>
    <% if can? :destroy, post %>
    <div class="owner__admin">
      <%= button_to 'Delete', post_path(post.id), params: { post: { post_id: post.id} }, method: :delete %>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<%= render 'users/user_card', user: @user %>
<%= render 'layouts/alert', flash: flash %>
<% @posts_and_comments.each do |post| %>
  <% if post.commentsCounter > 0 %>
    <div class="group__box">
  <% end %>
  <%= render 'post_card', post: post, detailed: false %>
  <% if post.commentsCounter > 0 %>
    <div class="card__box card__box-comments">
      <%= render partial: 'comments/comment_card', collection: post.comments.first(5), as: :comment %>
    </div>
    </div>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<div class="form__container">
<%= tag.h1('New Post', class: 'form__title') %>
<%= render 'layouts/alert', flash: flash %>
<%= form_with model: Post.new do |f| %>
  <%= f.text_field :title, placeholder: 'Title' %>
  <%= f.text_area :text, rows: 20, placeholder: 'Enter the content' %>
  <%= f.submit 'Save' %>
<% end %>
</div>

app/views/posts/show.html.erb
<%= render 'layouts/alert', flash: flash %>
<%= render 'post_card', post: @post, detailed: true %>
<% if @post.commentsCounter > 0 %>
  <div class="card__box">
    <%= tag.h3('Comments:', class: 'card__title') %>
    <%= render partial: 'comments/comment_card', collection: @post.comments, as: :comment %>
  </div>
<% end %>