config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show]
  end

  resources :posts, only: %i[new create destroy] do
    resources :comments, only: %i[index new create destroy]
    resources :likes, only: %i[create destroy]
  end

  namespace :api do
    devise_for :users, as: 'api', controllers: { sessions: 'api/sessions', registrations: 'api/registrations' }

    resources :users, only: %i[] do
      resources :posts, only: %i[index]
    end
  
    resources :posts, only: %i[] do
      resources :comments, only: %i[index create]
    end
  end

  # Defines the root path route ("/")
  root "users#index"
end

app/views/layouts/_alert.html.erb
<div class="alert__box">
  <% flash.each do |message_type, message| %>
    <%= tag.div(message, class: "alert alert-#{message_type}") %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <p>© 2022 Gabriela Sánchez Espirilla</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <%= link_to 'My Blog', users_path, class: 'brand' %>
    <nav>
      <%= link_to 'Home', users_path %>
      <%= link_to 'Profile', user_path(current_user.id) %>
      <%= link_to 'New Post', new_post_path, class: 'btn' %>
      <%= link_to 'Log Out', destroy_user_session_path, 'data-turbo-method': :delete %>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
    <%= render 'layouts/header', current_user: @current_user %>
    <% end %>
    <section class="main_section">
      <div class="container">
        <div class="box-block">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
        <%= yield %>
      </div>
    </section>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>